language: java

install:
  - cp .travis.m2.settings.xml $HOME/.m2/settings.xml
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test

deploy:
  - provider: script
    script: "mvn versions:set -DnewVersion=${TRAVIS_TAG} && mvn deploy"
    on:
      tags: true
  - provider: script
    script: mvn deploy
    on:
      tags: false
